version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kms
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kms_poc
      - POSTGRES_USER=poc_user
      - POSTGRES_PASSWORD=poc_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
